### ISSUE TITLE
Typo on line 14 of README.md

### ISSUE THREAD

**Issue by Sharpienero** [public-law/raspberry-pi-github-runner#2]
On line 14 of the README.md there is a typo. 

The fix is to change 'THis' to 'This'.

I went ahead and tried to branch and create a PR for you, but I am lacking the permissions.

**Comment by dogweather** [comment]
Thanks! Normally what you do is **fork** the repo, make the changes on a branch in your fork, and then submit a PR.

**Comment by dogweather** [comment]
Fixed.
